// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ColorSimilarityCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("color1")]
        public Color Color1 { get; set; }

        [JsonProperty("color2")]
        public Color Color2 { get; set; }

        [JsonProperty("rgb_distance")]
        public double RgbDistance { get; set; }

        [JsonProperty("rgb_similarity")]
        public double RgbSimilarity { get; set; }

        [JsonProperty("hsl_similarity")]
        public double HslSimilarity { get; set; }

        [JsonProperty("overall_similarity")]
        public double OverallSimilarity { get; set; }

        [JsonProperty("delta_e")]
        public double DeltaE { get; set; }

        [JsonProperty("hue_difference")]
        public double HueDifference { get; set; }

        [JsonProperty("saturation_difference")]
        public long SaturationDifference { get; set; }

        [JsonProperty("lightness_difference")]
        public double LightnessDifference { get; set; }

        [JsonProperty("similarity_category")]
        public string SimilarityCategory { get; set; }

        [JsonProperty("are_identical")]
        public bool AreIdentical { get; set; }
    }

    public partial class Color
    {
        [JsonProperty("hex")]
        public string Hex { get; set; }

        [JsonProperty("rgb")]
        public Rgb Rgb { get; set; }

        [JsonProperty("hsl")]
        public Hsl Hsl { get; set; }
    }

    public partial class Hsl
    {
        [JsonProperty("h")]
        public double H { get; set; }

        [JsonProperty("s")]
        public long S { get; set; }

        [JsonProperty("l")]
        public double L { get; set; }
    }

    public partial class Rgb
    {
        [JsonProperty("r")]
        public long R { get; set; }

        [JsonProperty("g")]
        public long G { get; set; }

        [JsonProperty("b")]
        public long B { get; set; }
    }
}
